# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache drivers
      uses: actions/cache@v4
      with:
        # In order:
        # * Driver for linux
        # * Driver for macOS
        # * Driver for windows
        path: |
          ~/.cache/ms-playwright-go
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-go-firefox-${{ hashFiles('**/run.go') }}

    - run: |
        go install ./...
        playwright install --with-deps firefox
        go run .
        cat instagram.csv
    

